version: "3.8"

services:
  frontend:
    container_name: "frontend-server"
    build:
      context: ./frontend
    ports:
      - "5173:5173"
  
  backend:
    container_name: "backend-server"
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ${DB_VOLUME}:/db_volume
    env_file:
      - .env
    environment:
      - DB_URL=sqlite:////db_volume/database.db


      