"""Initial

Revision ID: 181d5d8c2341
Revises: 
Create Date: 2025-04-06 15:41:00.109462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181d5d8c2341'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federated_session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['federated_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_federated_session_logs_id'), 'federated_session_logs', ['id'], unique=False)
    op.add_column('training_data_transfers', sa.Column('parent_filename', sa.String(), nullable=False))
    op.add_column('training_data_transfers', sa.Column('datastats', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_data_transfers', 'datastats')
    op.drop_column('training_data_transfers', 'parent_filename')
    op.drop_index(op.f('ix_federated_session_logs_id'), table_name='federated_session_logs')
    op.drop_table('federated_session_logs')
    # ### end Alembic commands ###
