"""Add training_history column

Revision ID: 42ecb8768678
Revises: c21fc2b434e2
Create Date: 2025-05-01 17:38:37.146403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42ecb8768678"
down_revision: Union[str, None] = "c21fc2b434e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "federated_round_client_submissions",
        sa.Column("training_history", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("federated_round_client_submissions", "training_history")
    # ### end Alembic commands ###
