"""add client_count in fed session

Revision ID: 45052be3b9b7
Revises: 33f2b87552cc
Create Date: 2025-07-08 11:36:32.542259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45052be3b9b7'
down_revision: Union[str, None] = '33f2b87552cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('federated_sessions', sa.Column('no_of_recieved_weights', sa.Integer(), nullable=False))
    op.add_column('federated_sessions', sa.Column('no_of_left_clients', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('federated_sessions', 'no_of_left_clients')
    op.drop_column('federated_sessions', 'no_of_recieved_weights')
    # ### end Alembic commands ###
