"""enum change from int to string for training status

Revision ID: 7e20b68455c6
Revises: af5305492787
Create Date: 2025-07-22 14:16:26.335632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e20b68455c6"
down_revision: Union[str, None] = "af5305492787"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if conn.dialect.name == "sqlite":
        # 1. Create new table with Enum type for 'tag'
        op.create_table(
            "federated_session_logs_new",
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("session_id", sa.Integer, nullable=False),
            sa.Column("message", sa.String, nullable=False),
            sa.Column(
                "tag",
                sa.Enum(
                    "INFO",
                    "ERROR",
                    "SUCCESS",
                    "TRAINING",
                    "CLIENT_JOINED",
                    "WEIGHTS_RECEIVED",
                    "AGGREGATED_WEIGHTS",
                    "TEST_RESULTS",
                    "CLIENT_LEFT",
                    "PRIZE_NEGOTIATION",
                    name="federatedsessionlogtag",
                ),
                nullable=False,
            ),
            sa.Column("createdAt", sa.DateTime, nullable=True),
            sa.Column("updatedAt", sa.DateTime, nullable=True),
            sa.Column("deletedAt", sa.DateTime, nullable=True),
        )
        # 2. Copy data
        columns = [
            col["name"] for col in inspector.get_columns("federated_session_logs")
        ]
        columns_str = ", ".join(columns)
        conn.execute(
            sa.text(
                f"INSERT INTO federated_session_logs_new ({columns_str}) SELECT {columns_str} FROM federated_session_logs"
            )
        )
        # 3. Drop old table
        op.drop_table("federated_session_logs")
        # 4. Rename new table
        op.rename_table("federated_session_logs_new", "federated_session_logs")
    else:
        op.alter_column(
            "federated_session_logs",
            "tag",
            existing_type=sa.VARCHAR(length=17),
            type_=sa.Enum(
                "INFO",
                "ERROR",
                "SUCCESS",
                "TRAINING",
                "CLIENT_JOINED",
                "WEIGHTS_RECEIVED",
                "AGGREGATED_WEIGHTS",
                "TEST_RESULTS",
                "CLIENT_LEFT",
                "PRIZE_NEGOTIATION",
                name="federatedsessionlogtag",
            ),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if conn.dialect.name == "sqlite":
        # 1. Create new table with VARCHAR type for 'tag'
        op.create_table(
            "federated_session_logs_old",
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("session_id", sa.Integer, nullable=False),
            sa.Column("message", sa.String, nullable=False),
            sa.Column("tag", sa.VARCHAR(length=17), nullable=False),
            sa.Column("createdAt", sa.DateTime, nullable=True),
            sa.Column("updatedAt", sa.DateTime, nullable=True),
            sa.Column("deletedAt", sa.DateTime, nullable=True),
        )
        # 2. Copy data
        columns = [
            col["name"] for col in inspector.get_columns("federated_session_logs")
        ]
        columns_str = ", ".join(columns)
        conn.execute(
            sa.text(
                f"INSERT INTO federated_session_logs_old ({columns_str}) SELECT {columns_str} FROM federated_session_logs"
            )
        )
        # 3. Drop old table
        op.drop_table("federated_session_logs")
        # 4. Rename new table
        op.rename_table("federated_session_logs_old", "federated_session_logs")
    else:
        op.alter_column(
            "federated_session_logs",
            "tag",
            existing_type=sa.Enum(
                "INFO",
                "ERROR",
                "SUCCESS",
                "TRAINING",
                "CLIENT_JOINED",
                "WEIGHTS_RECEIVED",
                "AGGREGATED_WEIGHTS",
                "TEST_RESULTS",
                "CLIENT_LEFT",
                "PRIZE_NEGOTIATION",
                name="federatedsessionlogtag",
            ),
            type_=sa.VARCHAR(length=17),
            existing_nullable=False,
        )
