"""Remove Global Model Weights, Client Model Weights and Benchmark Table

Revision ID: 8d9aeba6444d
Revises: 63f4f64bd954
Create Date: 2025-04-24 19:47:40.049660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8d9aeba6444d'
down_revision: Union[str, None] = '63f4f64bd954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_model_weights')
    op.drop_table('global_model_weights')
    op.drop_index('idx_benchmarks_task', table_name='benchmarks')
    op.drop_index('idx_benchmarks_time', table_name='benchmarks')
    op.drop_index('ix_benchmarks_benchmark_id', table_name='benchmarks')
    op.drop_index('ix_benchmarks_created_at', table_name='benchmarks')
    op.drop_index('ix_benchmarks_task_id', table_name='benchmarks')
    op.drop_table('benchmarks')
    op.add_column('tasks', sa.Column('benchmark', sa.JSON(), nullable=True))
    op.drop_column('tasks', 'temp_benchmark')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('temp_benchmark', sqlite.JSON(), nullable=True))
    op.drop_column('tasks', 'benchmark')
    op.create_table('benchmarks',
    sa.Column('benchmark_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('metric_value', sa.FLOAT(), nullable=False),
    sa.Column('training_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['federated_sessions.id'], ),
    sa.PrimaryKeyConstraint('benchmark_id')
    )
    op.create_index('ix_benchmarks_task_id', 'benchmarks', ['task_id'], unique=False)
    op.create_index('ix_benchmarks_created_at', 'benchmarks', ['created_at'], unique=False)
    op.create_index('ix_benchmarks_benchmark_id', 'benchmarks', ['benchmark_id'], unique=False)
    op.create_index('idx_benchmarks_time', 'benchmarks', ['created_at'], unique=False)
    op.create_index('idx_benchmarks_task', 'benchmarks', ['task_id'], unique=False)
    op.create_table('global_model_weights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('weights', sqlite.JSON(), nullable=True),
    sa.Column('createdAt', sa.DATETIME(), nullable=True),
    sa.Column('updatedAt', sa.DATETIME(), nullable=True),
    sa.Column('deletedAt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['federated_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_model_weights',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submission_id', sa.INTEGER(), nullable=True),
    sa.Column('weights', sqlite.JSON(), nullable=False),
    sa.Column('createdAt', sa.DATETIME(), nullable=True),
    sa.Column('updatedAt', sa.DATETIME(), nullable=True),
    sa.Column('deletedAt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['federated_round_client_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    # ### end Alembic commands ###
