"""User Name field added

Revision ID: acdaa51b4bfe
Revises: 36af4293fc8c
Create Date: 2025-09-13 07:00:33.962179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acdaa51b4bfe"
down_revision: Union[str, None] = "36af4293fc8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.String(), nullable=False, server_default="User")
    )
    op.drop_column("users", "data_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("data_url", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###
