"""tasks schema changed

Revision ID: af5305492787
Revises: b7055be3a1b7
Create Date: 2025-07-14 16:55:48.357568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5305492787'
down_revision: Union[str, None] = 'b7055be3a1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('federated_session_logs', sa.Column('tag', sa.Enum('FAILED', 'CANCELLED', 'CREATED', 'ACCEPTING_CLIENTS', 'STARTED', 'COMPLETED', name='trainingstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('federated_session_logs', 'tag')
    # ### end Alembic commands ###
