"""Added Table TrainingDataTransfer

Revision ID: bdce842571cd
Revises: 76deb0b472cb
Create Date: 2025-03-21 16:33:05.306100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdce842571cd'
down_revision: Union[str, None] = '76deb0b472cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_data_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_name', sa.String(), nullable=False),
    sa.Column('num_datapoints', sa.Integer(), nullable=False),
    sa.Column('data_path', sa.String(), nullable=False),
    sa.Column('transferredAt', sa.DateTime(), nullable=False),
    sa.Column('approvedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_data_transfers_id'), 'training_data_transfers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_data_transfers_id'), table_name='training_data_transfers')
    op.drop_table('training_data_transfers')
    # ### end Alembic commands ###
