"""wait_time error

Revision ID: d091759bfcd0
Revises: 45052be3b9b7
Create Date: 2025-07-08 12:36:25.151825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd091759bfcd0'
down_revision: Union[str, None] = '45052be3b9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('federated_sessions', 'wait_till')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('federated_sessions', sa.Column('wait_till', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
